In [199]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [200]:
df = pd.read_csv("IMDB Dataset.csv")

In [201]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [202]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [203]:
unique_emotions = df['sentiment'].unique()
emotion_numbers = {}
i = 0
for emo in unique_emotions:
  emotion_numbers[emo] = i
  i +=1

df['sentiment'] = df['sentiment'].map(emotion_numbers)

In [204]:
df

                                                  review  sentiment
0      One of the other reviewers has mentioned that ...          0
1      A wonderful little production. <br /><br />The...          0
2      I thought this was a wonderful way to spend ti...          0
3      Basically there's a family where a little boy ...          1
4      Petter Mattei's "Love in the Time of Money" is...          0
...                                                  ...        ...
49995  I thought this movie did a down right good job...          0
49996  Bad plot, bad dialogue, bad acting, idiotic di...          1
49997  I am a Catholic taught in parochial elementary...          1
49998  I'm going to have to disagree with the previou...          1
49999  No one expects the Star Trek movies to be high...          1

[50000 rows x 2 columns]

In [205]:
df['review'] = df['review'].apply(lambda x : x.lower())

In [206]:
import string

def rem_punch(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [207]:
df['review']=df['review'].apply(rem_punch)

In [208]:
df.head()

                                              review  sentiment
0  one of the other reviewers has mentioned that ...          0
1  a wonderful little production br br the filmin...          0
2  i thought this was a wonderful way to spend ti...          0
3  basically theres a family where a little boy j...          1
4  petter matteis love in the time of money is a ...          0

In [209]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['review'] = df['review'].apply(remove_numbers)

In [210]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['review'] = df['review'].apply(remove_emojis)

In [211]:
df.head()

                                              review  sentiment
0  one of the other reviewers has mentioned that ...          0
1  a wonderful little production br br the filmin...          0
2  i thought this was a wonderful way to spend ti...          0
3  basically theres a family where a little boy j...          1
4  petter matteis love in the time of money is a ...          0

In [215]:
import nltk

In [216]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [217]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [218]:
stop_words = set(stopwords.words('english'))

In [222]:
df.loc[1]['review']

'a wonderful little production br br the filming technique is very unassuming very oldtimebbc fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece br br the actors are extremely well chosen michael sheen not only has got all the polari but he has all the voices down pat too you can truly see the seamless editing guided by the references to williams diary entries not only is it well worth the watching but it is a terrificly written and performed piece a masterful production about one of the great masters of comedy and his life br br the realism really comes home with the little things the fantasy of the guard which rather than use the traditional dream techniques remains solid then disappears it plays on our knowledge and our senses particularly with the scenes concerning orton and halliwell and the sets particularly of their flat with halliwells murals decorating every surface are terribly well done'

In [223]:
def remove(txt):
  words = txt.split()
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)

  return ' '.join(cleaned)

In [224]:
df['review'] = df['review'].apply(remove)

In [225]:
df.loc[1]['review']

'wonderful little production br br filming technique unassuming oldtimebbc fashion gives comforting sometimes discomforting sense realism entire piece br br actors extremely well chosen michael sheen got polari voices pat truly see seamless editing guided references williams diary entries well worth watching terrificly written performed piece masterful production one great masters comedy life br br realism really comes home little things fantasy guard rather use traditional dream techniques remains solid disappears plays knowledge senses particularly scenes concerning orton halliwell sets particularly flat halliwells murals decorating every surface terribly well done'

In [226]:
df.head()

                                              review  sentiment
0  one reviewers mentioned watching oz episode yo...          0
1  wonderful little production br br filming tech...          0
2  thought wonderful way spend time hot summer we...          0
3  basically theres family little boy jake thinks...          1
4  petter matteis love time money visually stunni...          0

In [228]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['review'], df['sentiment'], test_size=0.20, random_state=42)

In [229]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)


nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)


pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))

0.8592

In [230]:
pred_bow

array([0, 0, 1, ..., 0, 1, 1])

In [231]:
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)


nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [232]:
y_pred = nb2_model.predict(X_test_tfidf)

In [233]:
print(accuracy_score(y_test, y_pred))

0.8694

In [234]:
from sklearn.linear_model import LogisticRegression

In [235]:
logistic_model = LogisticRegression(max_iter=1000)

In [236]:
logistic_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [237]:
log_pred = logistic_model.predict(X_test_tfidf)

In [238]:
print(accuracy_score(y_test,log_pred ))

0.8955